[package]
name = "partydiscord-rust"
version = "0.1.0"
authors = ["Skye Viau <skye.viau@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8.6"
reqwest = "0.10.4"
warp = "0.2.2"